blank_issues_enabled: false
contact_links:
  - name: NovaDial Feature Requests and Bug Reports
    url: https://github.com/dhilipmpms/NovaDial/discussions
    about: Please ask and answer questions here.
